{% set name = "scanpy" %}
{% set version = "1.4.6" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: 94fc75652e8cce8f12b9eb4e21e05f9d73a9475a181434f8e7a4bfa836334b68

build:
  number: 0
  noarch: generic
  entry_points:
    - scanpy=scanpy.cli:console_main
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - pip
    - python
  run:
    - anndata >=0.6.22.post1
    - h5py >=2.10.0
    - importlib_metadata >=0.7
    - joblib
    - legacy-api-wrap
    - matplotlib-base ==3.0.*
    - natsort
    - networkx
    - numba >=0.41.0
    - packaging
    - pandas >=0.21
    - patsy
    - python
    - scikit-learn >=0.21.2
    - scipy >=1.3
    - seaborn
    - setuptools_scm
    - statsmodels >=0.10.0rc2
    - tables
    - tqdm
    - umap-learn >=0.3.10

test:
  imports:
    - scanpy
  commands:
    - scanpy --help

about:
  home: "https://scanpy.readthedocs.io/en/latest/"
  license: BSD-3
  license_family: BSD
  summary: "Single-Cell Analysis in Python."

extra:
  identifiers:
    - doi:10.1186/s13059-017-1382-0
