{% set PYOMERO_VERSION = "5.4.10" %}
{% set PYOMERO_UPLOAD_VERSION = "5.6.2_2.0.0" %}

package:
  name: pyomero-upload
  version: '{{ PYOMERO_UPLOAD_VERSION }}'

source:
  url: 'https://github.com/SynthSys/pyOmeroUpload/archive/v{{ PYOMERO_UPLOAD_VERSION }}.tar.gz'
  sha256: 25a37ad9111d6fbd7db8d2d57a6f5717dc4c9b3a84974e420fd7ba1e16f57e07

build:
  noarch: python
  number: 0
  script: python -m pip install . --ignore-installed --no-deps -vv

requirements:
  host:
    - setuptools
    - python <3
  run:
    - python <3
    - zeroc-ice 3.6
    - 'python-omero {{ PYOMERO_VERSION }}'
    - pillow
    - enum34
    - pyyaml
    - pandas
    - scipy
    - requests
    - numpy
    - filetype
    - future

test:
  imports:
    - random
    - omero
    - omero.gateway

about:
  home: http://www.synthsys.ed.ac.uk/
  license: MIT
  license_file: LICENSE
  summary: Client library offering helper methods to upload data to an OMERO server.

