{% set name = "strling" %}
{% set version = "0.1.0" %}
{% set sha256 = "9da4963574c44ccee529834fd594818955c367abb9083dc0fc972286d6b3f728" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/quinlan-lab/STRling/releases/download/v0.1.0/strling
  sha256: {{ sha256 }}

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}

test:
  commands:
    - strling --help

about:
  home: https://github.com/quinlan-lab/STRling
  license: MIT
  summary: STRling (pronounced like “sterling”) is a method to detect large STR expansions from short-read sequencing data.