{% set name = "singlem" %}
{% set version = "0.13.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ba1f629ae89b05d0fd87e978bf0094dad5bac1bece56fb1d700f1987fb424cd8

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - pip
    - python >=3.6
    - nose >=1.0
  run:
    - python >=3.6
    - graftm >=0.12.2
    - extern >=0.0.4
    - tempdir >=0.6
    - biopython >=1.64
    - dendropy >=0.4.0
    - pandas >=0.19.2
    - biom-format >=2.1.6
    - orator >=0.9.7
    - squarify >=0.3.0
    - matplotlib-base >=2.0.2
    - smafa >=0.5.0
    - vsearch

test:
  imports:
    - singlem
  requires:
    - nose >=1.0
  commands:
    - singlem -h

about:
  home: https://github.com/wwood/singlem
  license: GNU General Public v3 (GPLv3)
  license_family: GPL3
  license_file: LICENSE
  summary: 'SingleM is a tool to find the abundances of discrete operational taxonomic units (OTUs) directly from shotgun metagenome data, without heavy reliance on reference sequence databases. It is able to differentiate closely related species even if those species are from lineages new to science.'
